### ISSUE TITLE
[Research] - Evaluate and create personas

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#6]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
Our aim is to identify the roles in the BPM lifecycle. On the basis of these roles, we want to create personas and evaluate how AI can support them.

Canva Board (Personas): https://www.canva.com/design/DAFhegEdNkQ/m0VaCgBhuoCbfVXWimHBHg/edit?utm_content=DAFhegEdNkQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Research on BPM Lifecycle
- [x] Create Template
- [x] Create personas
```

# Acceptance
* We understand what the BPM Lifecycle is and what roles are involved.
* We have personas and collect ideas how AI can help them

**Comment by manuw99** [comment]
https://doi-org.ezproxy.hs-augsburg.de/10.1007/978-3-662-56509-4

Fundamentals of Business Process Management, Chapter 1.4 BPM Lifecycle (p.17-27)

**Comment by manuw99** [comment]
rgalgj

**Comment by manuw99** [comment]
### Final Overview of specified personas:



![Persona #1_ Management (CFO)](https://github.com/Miragon/miranum-copilot/assets/129979987/cf9c3799-8f49-4dd6-b8fe-89a71044eb86)
![Business Analyst (BA)](https://github.com/Miragon/miranum-copilot/assets/129979987/f2f4cde9-b459-4730-8963-aaad918c8d01)
![Process Owner (PO)](https://github.com/Miragon/miranum-copilot/assets/129979987/e53bbade-2394-4864-92fd-4c5251cbc30f)
![Quality assurance manager (QAM)](https://github.com/Miragon/miranum-copilot/assets/129979987/183a7142-1354-41cb-acc2-94176b2eba40)
![System Engineer](https://github.com/Miragon/miranum-copilot/assets/129979987/52fd9afa-8a8d-4787-ad19-bfdc33b5c8b5)
