### ISSUE TITLE
[Research] - Research to what extent ChatGPT understands BPMN

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-copilot#7]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
We want to know to what extent ChatGPT can help in developing a bpmn diagram.
Possible questions could be:
* Can ChatGPT create simple but correct BPMN syntax?
* Are newcomers to BPMN able to understand ChatGPT's answers?

**Comment by Hafflgav** [comment]
Sounds good to me! 💯

**Comment by peterhnm** [comment]
Ideas:

* BPMN
    * Ask ChatGPT about BPMN (e.g What is a service task, Which gateway types exist, ...)
    * Generate examples to help to understand BPMN concepts
    * Give ChaptGPT the xml content and let it describe the process as a ordered list
    * Let ChatGPT generate a BPMN Model for Camunda 7 or 8
    * Give ChatGPT a BPMN Model and check for Best Practices

* JSON Schema
    * Give ChatGPT an JSON and let it generate JSON Schema
    * Let ChatGPT generate test data for given JSON Schema
